apiVersion: apps/v1
kind: Deployment
metadata:
  name: <+service.name>
spec:
  replicas: 1
  template:
    metadata:
      name: <+service.name>
      labels:
        app: <+pipeline.identifier>
    spec:
      containers:
      - image: tomcat:<+serviceVariables.version>
        name: <+service.name>
